#!/usr/bin/env python3

import argparse

from lib.govuk_assets import install_govuk_assets, remove_govuk_assets
from lib.term_colour import notify, status_ok


def main():
    args = get_args()

    if args.clean:
        remove_govuk_assets(args.app_dir)

    install_govuk_assets(args.app_dir, logger=log)


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--app-dir', default='app', help="""
        Relative path to app module""".strip())
    parser.add_argument('--clean', action='store_true', help="""
        Remove installed files""".strip())

    return parser.parse_args()


def log(msg):
    if msg == 'Done':
        status_ok(msg)
    else:
        notify('\n' + msg)


if __name__ == '__main__':
    import sys
    sys.exit(main())
