#!/usr/bin/env python3

import argparse

from lib.script_utils import virtualenv, environment


def main():
    args = get_args()
    return run_app(args.host, args.port)


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--host', default='127.0.0.1', help="""
        Bind to hostname""".strip())
    parser.add_argument('-p', '--port', default=5000, type=int, help="""
        Bind to port""".strip())

    return parser.parse_args()


def run_app(host, port):
    from app.factory import create_app
    app = create_app()
    return app.run(host=host, port=port)


if __name__ == '__main__':
    import sys

    with environment(), virtualenv():
        sys.exit(main())
