#!/usr/bin/env python3

import argparse

from lib.govuk_assets import install_govuk_assets
from lib.script_utils import virtualenv, environment
from lib.term_colour import notify, status_ok


def main():
    args = get_args()
    return run_app(args.host, args.port)


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--host', default='127.0.0.1', help="""
        Bind to hostname""".strip())
    parser.add_argument('-p', '--port', default=5000, type=int, help="""
        Bind to port""".strip())

    return parser.parse_args()


def run_app(host, port):
    from app.factory import create_app
    app = create_app()

    import os
    if 'WERKZEUG_RUN_MAIN' not in os.environ:
        notify('\nRunning web app')

    return app.run(
        host=host, port=port, ssl_context=('server.crt', 'server.key'))


if __name__ == '__main__':
    import sys

    install_govuk_assets('app')

    try:
        with environment(), virtualenv():
            sys.exit(main())

    except KeyboardInterrupt:
        status_ok('\nDone')
